services:
  - type: web
    name: learner-circle-app
    env: node
    buildCommand: npm run render-build
    startCommand: npm start
    plan: starter
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: learner-circle-db
          property: connectionString

databases:
  - name: learner-circle-db
    databaseName: learner_circle
    user: learner_circle_user
    plan: starter